apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTRhSXdXZTFHM3RrUnRuUmZ6cVVhL09vbEJJaWt2Nld5TG5LcCtjT0ZwdksvCmpKTy8xNHlHcUpHNjBURjhIOTd4UU9idjBSUjB3TkI2K1U2TkVIVVRFNUxaY0JBYXE3eDR2cE1qTjdnMmx3eTQKTWFpWVZ2bDBIUFlhQURXaTNvT1VCNG5ESlBPVzR2SUZsMTFrY0JsYVU0bEdnUmlkbWhHcFpWRThEM0gyNlUxVQpzOERtNFA1RFJnb2h6RHZoR0dCb3pRZGdnSWxQaXpDTm9zK09lOFNNbUEvVEJ0MHhoNk5KRnluYUNRQWxLVEdhCllpeE5tQUpHOGhEREVXUWZQNTVMM25ndUUzQWczaFNyRWpvZThGR2gyb3NQcFpXUUVkTjVJT1lFRTF1Q1kzeFQKQ2VNa3BvZ1Rad1J0K1lqQktjek5KeFcxSG54eFdDbVlmMHE1cmF1NEdRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSFJIQjlVN1krQU05SW1mdzUxK2JPYkFyRWgvVHZpZkIrT28yQTZaak1pWlkrWEU2cDcwCmhBSjdZa05EUTNjOUJzd1V3eklmQzJWOGx3UHprNTV3WkI2eWlxc3kxekUrMmVXMlF0VTh4QzNXVTdQUzZ2Q3UKcUVFVkwwdy9HcnlMdmxCS3AyWXZ0aUxhZHl4Z3VuOFZoYW55bzFrdHB0cXZEYmUzS2FxWGV4NXVYWHlITUNoaQowU3FXTnhGa3dkSWp1SExVU042ZjU0QUpSOWxSMTliU2ZJNzk3bytUN0hhdXMrQTFQZEFVWDdjcld5anNGQU9CCk1rQUFtenQrSmNrcjZWWWRwdm1QNllDU0t4SWwwd28xRXJUN3J0MStIZ0lFTnZGWVZIYUdjVlkrUk9iVWdDeTcKM2FXdFVTMlRmOWx0T3dENlRhSEMvc2JtejRsZGJEL1o0VzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo= 
  signerName: kubernetes.i/kube-apiserver-client
  usages:
  - client auth
  
